---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Leu.
--- DateTime: 07/02/18 16:34
---

function onUse(player, item, fromPosition, target, toPosition, isHotkey)
    player:sendRewardWindow()
    return true
end
